version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 15
    target-branch: master
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 10
    target-branch: master
